:toc: macro
:toc-title:
:toclevels: 9

# Chapter 14 – Testing

toc::[]



## Notes

* Testing Haskell code is necessary because the compiler cannot guarantee that there will not be runtime exceptions. Aside: Other tools like link:https://github.com/ucsd-progsys/liquidhaskell[Liquid Haskell] exist because of this fact, learn more about LH through its link:http://ucsd-progsys.github.io/liquidhaskell-tutorial/[introduction].

* Among several testing libraries two available are `Hspec` and `QuickCheck`.

* Hspec is focused on `Spec Testing` while QuickCheck is focused on `Property Testing`.

* A Spec Test is like a Unit Test test in that it is at the level of individual functions and checks that a function given an input (its argument(s)) produces the expected output. A Spec Test is unlike a Unit Test in that it aims to be readable by programmers/non-programmers alike.

* A Property Test generates random inputs and checks that the outputs satisfy some property or law. To accomplish this check it permits the user to supply a predicate function that encodes the property/law which must hold for the whole gamut of possible inputs.

* The principal authoring difference between a Unit Test and Property Test is that in the former the author _may_ limit their thinking to ad-hoc in/out matches while in the former the author _must_ be more general in their thinking to find a property or law (AKA pattern). Realizing properties about a function is generally favorable to ad-hoc in/out matches because the former can potentially apply to a great number of in/out matches making it easier to reason about in use and in sharing/communicating.

* A limitation of Spec/Unit Testing is that integrations between units are not tested.

* QuickCheck defaults to generating 100 random inputs.

* Not all programs can leverage a Property Test: They must have an "assertable truth-valued" property in the first place.



### QuickCheck

* Initially there are few key parts we play with:

** Three functions: `sample`, `sample'`, `arbitrary`

** One Type Class: `Arbitrary a`

** One Type: `Gen a`

* The `arbitrary` "function" is a actually a value that dispatches based on its type. It does not actually accept any arguments. The signature is `Arbitrary a => Gen a` and can be used like `arbitrary :: Gen String`. This example works because `String` implements the `Arbitrary` Type Class. The type of value itself is a generator. It appears to be an opaque value that is somehow used by e.g. `sample` to produce a random value. It is important to observe that `arbitrary` is _pure_ while `sample` is not. Therefore the randomness itself must not be coming from `arbitrary` but some other source that uses/feeds `arbitrary`. But I don't really understand how yet.

* The `sample` function receives a single argument of type `Gen a` and in turn prints out random data to stdout. Its type is `Show a => Gen a -> IO ()`.

** Given the type of `sample` and `arbitrary` combined `a` must be in two Type Classes: `Show` and `Arbitrary`.

* The `sample'` function is just like `sample` without the `Show` Type Class requirement and returns `IO [a]` instead of `IO ()`.

* The Type `IO` is used by `sample` and `sample'` because of the way it gets random data: an impure process wherein a global resource is accessed. The precise mechanics of this process are not explained by the book at least yet.

* Additional generator functions are introduced:

** `elements` creates a generator that selects one value from a list. Its type is simply `[a] -> Gen a`.

** `choose` creates a generator that selects one value from a tuple. Its type is a bit odd and I do not understand it currently: `random-1.1:System.Random.Random a => (a, a) -> Gen a`.

** `frequency` is like `elements` but the generator created biases selection according to the definition given. The type is `[(Int, Gen a)] -> Gen a`. The bias works as a total of the given frequency numbers. For example given:
+
```haskell
frequency [(2, pure Foo), (4, pure Bar), (2, pure Qux)]
```
+
The probabilities would be: `1/4 Foo | 1/4 Qux | 1/2 Bar`.

* Several pages probe the reader to create her own generators. For example:
+
```haskell
genMaybe :: Arbitrary a => Gen (Maybe a)
genMaybe = do
  a <- arbitrary
  frequency [(1, Nothing),
             (3, Just a)]

```
+
```haskell
==> sample (genMaybe :: Gen (Maybe Integer))
Just 0
Nothing
Just 0
Just 1
Just (-8)
Just 10
Just (-1)
Nothing
Nothing
Nothing
Just 7
```

* Ambiguous types prevent a Haskell program from compiling but in `ghci` there is a feature which causes them to default to unit (`()`). For example:

```
==> sample arbitrary

<interactive>:4:1: Warning:
    Defaulting the following constraint(s) to type ‘()’
      (Show a0) arising from a use of ‘sample’ at <interactive>:4:1-6
      (Arbitrary a0)
        arising from a use of ‘arbitrary’ at <interactive>:4:8-16
    In the first argument of ‘GHC.GHCi.ghciStepIO ::
                                IO a_a3KL -> IO a_a3KL’, namely
      ‘sample arbitrary’
    In a stmt of an interactive GHCi command:
      it <- GHC.GHCi.ghciStepIO :: IO a_a3KL -> IO a_a3KL
            (sample arbitrary)
()
()
()
()
()
()
()
()
()
()
()
```
But if we try to compile `sample arbitrary`:

```
Main.hs:7:8:
    No instance for (Show a0) arising from a use of ‘sample’
    The type variable ‘a0’ is ambiguous
    Note: there are several potential instances:
      instance Show HUnit-1.3.0.0:Test.HUnit.Lang.HUnitFailure
        -- Defined in ‘HUnit-1.3.0.0:Test.HUnit.Lang’
      instance Show HUnit-1.3.0.0:Test.HUnit.Lang.Location
        -- Defined in ‘HUnit-1.3.0.0:Test.HUnit.Lang’
      instance Show HUnit-1.3.0.0:Test.HUnit.Lang.Result
        -- Defined in ‘HUnit-1.3.0.0:Test.HUnit.Lang’
      ...plus 57 others
    In the expression: sample arbitrary
    In an equation for ‘test’: test = sample arbitrary

Main.hs:7:15:
    No instance for (Arbitrary a0) arising from a use of ‘arbitrary’
    The type variable ‘a0’ is ambiguous
    Note: there are several potential instances:
      instance [overlap ok] [safe] (RealFloat a, Arbitrary a) =>
                                   Arbitrary (Data.Complex.Complex a)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
      instance [overlap ok] [safe] (Arbitrary a, Arbitrary b) =>
                                   Arbitrary (Either a b)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
      instance [overlap ok] [safe] Data.Fixed.HasResolution a =>
                                   Arbitrary (Data.Fixed.Fixed a)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
      ...plus 26 others
    In the first argument of ‘sample’, namely ‘arbitrary’
    In the expression: sample arbitrary
    In an equation for ‘test’: test = sample arbitrary
```

** To make GHC act like `ghci` use the flag `-XExtendedDefaultRules`.
